### ISSUE TITLE
cssとjsが適用されない

### ISSUE THREAD

**Issue by Kumaharu** [yyk284/onlinekateikyousi#17]
> 

<img width="1044" alt="スクリーンショット 2019-08-25 19 03 57" src="https://user-images.githubusercontent.com/23465282/63649052-67e50080-c76b-11e9-88a6-7fe6daa4767c.png">

相対パスで指定したんだけどこれだけじゃ適用されない、、、
<link rel="stylesheet" href="../../sass/style.css">
<link rel="stylesheet" href="../../sass/slide.css">
<script src="../../js/openclose.js"></script>
<script src="../../js/fixmenu_pagetop.js"></script>
<script src="../../js/styleswitcher.js"></script>

**Comment by RyumaRyama** [comment]
laravelでの適応方法がありそう
単純なpathじゃない気がする

**Comment by RyumaRyama** [comment]
http://gamushiros.hatenablog.com/entry/2016/08/19/234635

**Comment by Kumaharu** [comment]
とりあえず動いた。リュウマの方法で動いた。
アセットってやり方もあるらしい
http://gamushiros.hatenablog.com/entry/2016/08/19/234635
